// Landmark recording format, written by the Mirror debug panel ("Record landmarks", SPEC §13 M3)
// and replayed by tests in __tests__/replay.test.ts.
import type { Landmark } from './landmarks';

export interface LandmarkRecording {
  version: 1;
  exerciseId: string;
  /** "recorded" = real camera; "synthetic" = generated by the test simulator. */
  source: 'recorded' | 'synthetic';
  width: number;
  height: number;
  recordedAt: string;
  frames: RecordedFrame[];
}

export interface RecordedFrame {
  /** Milliseconds since the recording started. */
  t: number;
  /** 33 × [x, y, z, visibility], or null when nobody was detected. */
  lm: number[][] | null;
  /** Optional world landmarks, 33 × [x, y, z]. */
  w?: number[][] | null;
}

const r = (v: number, d: number) => Math.round(v * 10 ** d) / 10 ** d;

export function encodeLandmarks(lms: Landmark[] | null): number[][] | null {
  if (!lms) return null;
  return lms.map((l) => [r(l.x, 4), r(l.y, 4), r(l.z ?? 0, 4), r(l.visibility ?? 1, 2)]);
}

export function encodeWorld(lms: Landmark[] | null | undefined): number[][] | null {
  if (!lms) return null;
  return lms.map((l) => [r(l.x, 4), r(l.y, 4), r(l.z ?? 0, 4)]);
}

export function decodeLandmarks(lm: number[][] | null): Landmark[] | null {
  if (!lm) return null;
  return lm.map(([x, y, z, visibility]) => ({ x, y, z, visibility }));
}

export function decodeWorld(w: number[][] | null | undefined): Landmark[] | null {
  if (!w) return null;
  return w.map(([x, y, z]) => ({ x, y, z, visibility: 1 }));
}
