import { FULL_BODY, LM } from '../pose/landmarks';
import type { ExerciseConfig, GuidedExerciseConfig } from './types';

export const miniSquat: ExerciseConfig = {
  tracking: 'live',
  id: 'mini_squat',
  name: 'Mini Squat',
  region: 'knee',
  kind: 'reps',
  cameraView: 'front',
  description: 'Feet hip-width apart, bend your knees slightly, then stand back up.',
  steps: [
    'Face the camera, feet hip-width apart.',
    'Bend your knees slightly, keeping them over your toes.',
    'Stand back up slowly.',
  ],
  requiredLandmarks: FULL_BODY,
  primaryAngle: { joint: 'knee', depth: true },
  side: 'both',
  startAngle: 170,
  targetAngle: 135,
  defaultSets: 3,
  defaultReps: 10,
  minRepSeconds: 0.8,
  faultRules: ['knee_valgus', 'weight_shift', 'torso_lean', 'not_high_enough'],
  angleLabel: 'Knee',
  cues: {
    intro: 'squat_intro',
    onRaising: 'squat_bend',
    onTop: 'hold',
    onLowering: 'squat_stand',
    onRep: 'rep_of',
    faults: {
      knee_valgus: 'knees_over_toes',
      weight_shift: 'weight_even',
      torso_lean: 'chest_up',
      not_high_enough: 'squat_lower',
    },
    onSetComplete: 'set_complete',
    onSessionComplete: 'session_complete',
  },
};

export const sitToStand: ExerciseConfig = {
  tracking: 'live',
  id: 'sit_to_stand',
  name: 'Sit to Stand',
  region: 'knee',
  kind: 'reps',
  cameraView: 'side',
  description: 'Sit side-on to the camera, then stand up fully and sit back down with control.',
  steps: [
    'Place a sturdy chair side-on to the camera and sit down.',
    'Stand up fully without using your hands if you can.',
    'Sit back down slowly.',
  ],
  requiredLandmarks: [LM.NOSE],
  primaryAngle: { joint: 'knee' },
  side: 'auto',
  startAngle: 95,
  targetAngle: 165,
  defaultSets: 2,
  defaultReps: 8,
  minRepSeconds: 1.2,
  faultRules: ['torso_lean', 'not_high_enough'],
  angleLabel: 'Knee',
  // Sitting makes the body look shorter, so allow a smaller body height.
  calibration: { minBodyHeight: 0.4 },
  cues: {
    intro: 'sts_intro',
    onRaising: 'sts_stand',
    onTop: 'sts_top',
    onLowering: 'sts_sit',
    onRep: 'rep_of',
    faults: {
      torso_lean: 'chest_up',
      not_high_enough: 'sts_stand_tall',
    },
    onSetComplete: 'set_complete',
    onSessionComplete: 'session_complete',
  },
};

export const singleLegBalance: ExerciseConfig = {
  tracking: 'live',
  id: 'single_leg_balance',
  name: 'Single-Leg Balance',
  region: 'knee',
  kind: 'hold',
  cameraView: 'front',
  description: 'Stand on one leg for 30 seconds with your hips level.',
  steps: [
    'Face the camera, standing near a wall or chair for support.',
    'Lift one foot off the floor.',
    'Hold for 30 seconds, keeping your hips level.',
  ],
  requiredLandmarks: FULL_BODY,
  side: 'auto',
  startAngle: 0,
  targetAngle: 0,
  holdSeconds: 30,
  defaultSets: 2,
  defaultReps: 1,
  minRepSeconds: 0,
  faultRules: ['pelvis_drop', 'knee_valgus'],
  angleLabel: 'Knee',
  cues: {
    intro: 'slb_intro',
    onRaising: 'slb_lift',
    onTop: 'slb_holding',
    onLowering: 'slb_lift',
    onRep: 'slb_done',
    faults: {
      pelvis_drop: 'keep_hips_level',
      knee_valgus: 'knee_over_toes_single',
    },
    onSetComplete: 'slb_switch',
    onSessionComplete: 'session_complete',
  },
};

const guided = (
  id: string,
  name: string,
  description: string,
  steps: string[],
  reps: number,
  secondsPerRep: number,
  sets = 3,
): GuidedExerciseConfig => ({
  tracking: 'guided',
  id,
  name,
  region: 'knee',
  description,
  steps,
  defaultSets: sets,
  defaultReps: reps,
  secondsPerRep,
  intro: `${id}_intro`,
});

export const kneeGuided: GuidedExerciseConfig[] = [
  guided(
    'quad_set',
    'Quadriceps Set',
    'Straighten the knee and tighten the thigh without lifting the leg.',
    ['Sit or lie with your leg straight.', 'Press the back of your knee down and tighten your thigh.', 'Hold for 5 seconds, then relax.'],
    10,
    7,
    4,
  ),
  guided(
    'straight_leg_raise',
    'Straight Leg Raise',
    'Lying down, keep the knee locked straight while lifting and lowering slowly.',
    ['Lie on your back, other knee bent.', 'Tighten your thigh and lift the straight leg to the height of the other knee.', 'Lower slowly.'],
    10,
    4,
  ),
  guided(
    'heel_slide',
    'Heel Slide',
    'Lying down, slide your heel towards you to bend the knee, then straighten.',
    ['Lie on your back with legs straight.', 'Slide your heel towards your bottom.', 'Slide it back out slowly.'],
    10,
    4,
  ),
  guided(
    'step_up',
    'Step-Up',
    'Step up onto a low step, leading with the recovering leg.',
    ['Stand facing a low, stable step.', 'Step up with the recovering leg, then bring the other foot up.', 'Step down slowly.'],
    10,
    4,
  ),
];
