import { FULL_BODY, LM } from '../pose/landmarks';
import type { ExerciseConfig, GuidedExerciseConfig } from './types';

export const shoulderAbduction: ExerciseConfig = {
  tracking: 'live',
  id: 'shoulder_abduction',
  name: 'Shoulder Abduction',
  region: 'shoulder',
  kind: 'reps',
  cameraView: 'front',
  description: 'Raise both arms out to the side, up to shoulder height, keeping your torso upright.',
  steps: [
    'Face the camera, arms by your sides.',
    'Raise both arms out to the side, up to shoulder height.',
    'Lower slowly and with control.',
  ],
  requiredLandmarks: [...FULL_BODY, LM.L_ELBOW, LM.R_ELBOW],
  primaryAngle: { joint: 'shoulder' },
  side: 'both',
  startAngle: 20,
  targetAngle: 90,
  defaultSets: 3,
  defaultReps: 10,
  minRepSeconds: 0.8,
  faultRules: ['torso_lean', 'asymmetry', 'elbow_bend', 'not_high_enough'],
  angleLabel: 'Shoulder',
  cues: {
    intro: 'abd_intro',
    onRaising: 'abd_raising',
    onTop: 'abd_top',
    onLowering: 'lower_slowly',
    onRep: 'rep_of',
    faults: {
      torso_lean: 'keep_torso_upright',
      asymmetry: 'raise_both_evenly',
      elbow_bend: 'keep_elbows_straight',
      not_high_enough: 'abd_raise_higher',
    },
    onSetComplete: 'set_complete',
    onSessionComplete: 'session_complete',
  },
};

export const shoulderFlexion: ExerciseConfig = {
  tracking: 'live',
  id: 'shoulder_flexion',
  name: 'Shoulder Flexion',
  region: 'shoulder',
  kind: 'reps',
  cameraView: 'side',
  description: 'Stand side-on to the camera and raise your arm forward and up, without arching your back.',
  steps: [
    'Turn side-on to the camera, arm by your side.',
    'Raise your arm forward and up as high as is comfortable.',
    'Lower slowly. Keep your back straight.',
  ],
  requiredLandmarks: [LM.NOSE],
  primaryAngle: { joint: 'shoulder' },
  side: 'auto',
  startAngle: 20,
  targetAngle: 150,
  defaultSets: 3,
  defaultReps: 10,
  minRepSeconds: 1.0,
  faultRules: ['back_arch', 'elbow_bend', 'not_high_enough'],
  angleLabel: 'Shoulder',
  cues: {
    intro: 'flex_intro',
    onRaising: 'flex_raising',
    onTop: 'hold',
    onLowering: 'lower_slowly',
    onRep: 'rep_of',
    faults: {
      back_arch: 'dont_arch_back',
      elbow_bend: 'keep_elbow_straight',
      not_high_enough: 'flex_raise_higher',
    },
    onSetComplete: 'set_complete',
    onSessionComplete: 'session_complete',
  },
};

const guided = (
  id: string,
  name: string,
  description: string,
  steps: string[],
  reps: number,
  secondsPerRep: number,
  sets = 3,
): GuidedExerciseConfig => ({
  tracking: 'guided',
  id,
  name,
  region: 'shoulder',
  description,
  steps,
  defaultSets: sets,
  defaultReps: reps,
  secondsPerRep,
  intro: `${id}_intro`,
});

export const shoulderGuided: GuidedExerciseConfig[] = [
  guided(
    'shoulder_external_rotation',
    'Shoulder External Rotation',
    'Elbow tucked at your side and bent to 90°, rotate the forearm outward.',
    ['Tuck your elbow against your side, bent to 90°.', 'Rotate your forearm outward, away from your belly.', 'Return slowly.'],
    12,
    4,
  ),
  guided(
    'shoulder_internal_rotation',
    'Shoulder Internal Rotation',
    'Elbow tucked at your side and bent to 90°, rotate the forearm inward.',
    ['Tuck your elbow against your side, bent to 90°.', 'Rotate your forearm inward, towards your belly.', 'Return slowly.'],
    12,
    4,
  ),
  guided(
    'pendulum_swing',
    'Pendulum Swing',
    'Lean on a table and let the arm hang loose, tracing small circles.',
    ['Lean forward with your good hand on a table.', 'Let the other arm hang loose.', 'Gently swing it in small circles.'],
    10,
    3,
    2,
  ),
];
