// Replays landmark recordings through the full SessionEngine (SPEC §12).
//
// Fixture files are named `<anything>_<exerciseId>_<N>reps.json` (e.g.
// `recorded_shoulder_abduction_10reps.json`) and are downloaded from the Mirror debug panel
// (?debug=1 → "Record landmarks"). Every fixture must replay to exactly N reps.
//
// The bundled `synthetic_…` fixture is generated by the simulator, not filmed. Record a real one
// on a phone and add it here before the final demo.
import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { getLiveExercise } from '../../exercises';
import { decodeLandmarks, decodeWorld, type LandmarkRecording } from '../recording';
import { SessionEngine } from '../sessionEngine';

const dir = join(__dirname, 'fixtures');
const files = readdirSync(dir).filter((f) => /_\d+reps\.json$/.test(f));

describe('recorded landmark replay', () => {
  it('has at least one fixture', () => {
    expect(files.length).toBeGreaterThan(0);
  });

  it.each(files)('%s replays to the expected rep count', (file) => {
    const expected = Number(/_(\d+)reps\.json$/.exec(file)![1]);
    const rec = JSON.parse(readFileSync(join(dir, file), 'utf8')) as LandmarkRecording;
    const engine = new SessionEngine(getLiveExercise(rec.exerciseId), { targetReps: expected, sets: 1 });
    let calibrationIssues = 0;
    for (const f of rec.frames) {
      const frame = engine.update(decodeLandmarks(f.lm), f.t, rec.width, rec.height, decodeWorld(f.w));
      calibrationIssues += frame.events.filter((e) => e.type === 'calibration').length;
    }
    const summary = engine.summary();
    expect(summary.reps).toBe(expected);
    expect(engine.currentPhase).toBe('complete');
    if (rec.source === 'synthetic') {
      // The synthetic recording walks in too close first, so calibration must have spoken up.
      expect(calibrationIssues).toBeGreaterThan(0);
    }
  });
});
